"""
Configuration-driven definition of SIET_DEFAULT_V1 magazine template.
Defines explicit geometric regions, text budgets, image bounds, and styling rules
for all 11 required page types.
"""

from app.modules.magazine.templates.template_schema import (
    CaptionRegionSpec,
    ImageRegionSpec,
    MagazineTemplateSpec,
    PageTypeSpec,
    TextRegionSpec,
)


def _build_cover_page_spec() -> PageTypeSpec:
    return PageTypeSpec(
        page_type="cover",
        display_name="Cover Page",
        description="Full-bleed magazine cover with prominent masthead, hero image, and headline.",
        maximum_images=1,
        headline_limits={"max_chars": 80, "max_words": 10},
        body_limits={"min_words": 15, "max_words": 50},
        alignment="center",
        text_regions=[
            TextRegionSpec(
                region_key="cover_masthead",
                role="header",
                x_pt=36.0,
                y_pt=40.0,
                width_pt=523.28,
                height_pt=55.0,
                font_size_min=24.0,
                font_size_max=32.0,
                font_family="times-bold",
                color_hex="#8B0000",
                align="center",
            ),
            TextRegionSpec(
                region_key="cover_subtitle",
                role="subheadline",
                x_pt=36.0,
                y_pt=100.0,
                width_pt=523.28,
                height_pt=25.0,
                font_size_min=10.0,
                font_size_max=12.0,
                font_family="helv",
                color_hex="#1A365D",
                align="center",
            ),
            TextRegionSpec(
                region_key="cover_headline",
                role="headline",
                x_pt=46.0,
                y_pt=580.0,
                width_pt=503.28,
                height_pt=90.0,
                font_size_min=18.0,
                font_size_max=24.0,
                font_family="times-bold",
                color_hex="#FFFFFF",
                align="left",
            ),
            TextRegionSpec(
                region_key="cover_summary",
                role="body",
                x_pt=46.0,
                y_pt=675.0,
                width_pt=503.28,
                height_pt=60.0,
                font_size_min=10.0,
                font_size_max=12.0,
                font_family="helv",
                color_hex="#F3F4F6",
                align="left",
            ),
            TextRegionSpec(
                region_key="cover_footer",
                role="footer",
                x_pt=36.0,
                y_pt=780.0,
                width_pt=523.28,
                height_pt=25.0,
                font_size_min=9.0,
                font_size_max=10.0,
                font_family="helv-bold",
                color_hex="#1A365D",
                align="center",
            ),
        ],
        image_regions=[
            ImageRegionSpec(
                region_key="cover_hero_img",
                role="hero",
                x_pt=36.0,
                y_pt=135.0,
                width_pt=523.28,
                height_pt=430.0,
                aspect_ratio="4:3",
                fit_mode="cover",
            )
        ],
    )


def _build_contents_page_spec() -> PageTypeSpec:
    return PageTypeSpec(
        page_type="contents",
        display_name="Table of Contents & Overview",
        description="Issue directory, editorial welcome, and featured event digests.",
        maximum_images=1,
        headline_limits={"max_chars": 60, "max_words": 8},
        body_limits={"min_words": 60, "max_words": 200},
        text_regions=[
            TextRegionSpec(
                region_key="contents_title",
                role="headline",
                x_pt=36.0,
                y_pt=45.0,
                width_pt=523.28,
                height_pt=40.0,
                font_size_min=20.0,
                font_size_max=24.0,
                font_family="times-bold",
                color_hex="#8B0000",
                align="left",
            ),
            TextRegionSpec(
                region_key="editorial_note",
                role="body",
                x_pt=36.0,
                y_pt=95.0,
                width_pt=320.0,
                height_pt=180.0,
                font_size_min=9.5,
                font_size_max=11.0,
                font_family="times",
                color_hex="#1F2937",
                align="left",
            ),
            TextRegionSpec(
                region_key="toc_items",
                role="body",
                x_pt=36.0,
                y_pt=290.0,
                width_pt=523.28,
                height_pt=480.0,
                font_size_min=9.0,
                font_size_max=11.0,
                font_family="helv",
                color_hex="#1F2937",
                align="left",
            ),
        ],
        image_regions=[
            ImageRegionSpec(
                region_key="contents_sidebar_img",
                role="secondary",
                x_pt=375.0,
                y_pt=95.0,
                width_pt=184.28,
                height_pt=180.0,
                aspect_ratio="1:1",
                fit_mode="cover",
            )
        ],
    )


def _build_event_page_spec() -> PageTypeSpec:
    return PageTypeSpec(
        page_type="event",
        display_name="Standard Event Page",
        description="Comprehensive reportage for institutional conferences and campus events.",
        maximum_images=2,
        headline_limits={"max_chars": 110, "max_words": 15},
        body_limits={"min_words": 60, "max_words": 350},
        text_regions=[
            TextRegionSpec(
                region_key="event_header",
                role="header",
                x_pt=36.0,
                y_pt=36.0,
                width_pt=523.28,
                height_pt=18.0,
                font_size_min=8.0,
                font_size_max=9.0,
                font_family="helv-bold",
                color_hex="#8B0000",
            ),
            TextRegionSpec(
                region_key="event_headline",
                role="headline",
                x_pt=36.0,
                y_pt=60.0,
                width_pt=523.28,
                height_pt=48.0,
                font_size_min=16.0,
                font_size_max=20.0,
                font_family="times-bold",
                color_hex="#1F2937",
            ),
            TextRegionSpec(
                region_key="event_subheadline",
                role="subheadline",
                x_pt=36.0,
                y_pt=112.0,
                width_pt=523.28,
                height_pt=22.0,
                font_size_min=10.0,
                font_size_max=12.0,
                font_family="helv-oblique",
                color_hex="#1A365D",
            ),
            TextRegionSpec(
                region_key="event_body",
                role="body",
                x_pt=36.0,
                y_pt=142.0,
                width_pt=300.0,
                height_pt=420.0,
                font_size_min=9.0,
                font_size_max=10.5,
                font_family="times",
                color_hex="#1F2937",
                align="justify",
            ),
            TextRegionSpec(
                region_key="event_meta_box",
                role="callout",
                x_pt=36.0,
                y_pt=580.0,
                width_pt=523.28,
                height_pt=80.0,
                font_size_min=9.0,
                font_size_max=10.0,
                font_family="helv",
                color_hex="#1F2937",
            ),
        ],
        image_regions=[
            ImageRegionSpec(
                region_key="event_main_img",
                role="hero",
                x_pt=350.0,
                y_pt=142.0,
                width_pt=209.28,
                height_pt=190.0,
                aspect_ratio="4:3",
                fit_mode="cover",
            ),
            ImageRegionSpec(
                region_key="event_secondary_img",
                role="secondary",
                x_pt=350.0,
                y_pt=370.0,
                width_pt=209.28,
                height_pt=190.0,
                aspect_ratio="4:3",
                fit_mode="cover",
            ),
        ],
        caption_regions=[
            CaptionRegionSpec(
                region_key="caption_main",
                associated_image_key="event_main_img",
                x_pt=350.0,
                y_pt=335.0,
                width_pt=209.28,
                height_pt=30.0,
                max_words=14,
            ),
            CaptionRegionSpec(
                region_key="caption_secondary",
                associated_image_key="event_secondary_img",
                x_pt=350.0,
                y_pt=563.0,
                width_pt=209.28,
                height_pt=25.0,
                max_words=14,
            ),
        ],
    )


def _build_achievement_victory_page_spec() -> PageTypeSpec:
    return PageTypeSpec(
        page_type="achievement_victory",
        display_name="Achievement & Victory Spotlight",
        description="Celebratory layout for prize winners, gold medals, hackathons, and research grants.",
        maximum_images=2,
        headline_limits={"max_chars": 100, "max_words": 14},
        body_limits={"min_words": 40, "max_words": 300},
        text_regions=[
            TextRegionSpec(
                region_key="victory_badge_header",
                role="callout",
                x_pt=36.0,
                y_pt=40.0,
                width_pt=523.28,
                height_pt=30.0,
                font_size_min=10.0,
                font_size_max=12.0,
                font_family="helv-bold",
                color_hex="#8B0000",
                align="center",
            ),
            TextRegionSpec(
                region_key="victory_headline",
                role="headline",
                x_pt=36.0,
                y_pt=75.0,
                width_pt=523.28,
                height_pt=50.0,
                font_size_min=18.0,
                font_size_max=22.0,
                font_family="times-bold",
                color_hex="#1A365D",
                align="center",
            ),
            TextRegionSpec(
                region_key="victory_body",
                role="body",
                x_pt=36.0,
                y_pt=135.0,
                width_pt=523.28,
                height_pt=180.0,
                font_size_min=10.0,
                font_size_max=11.5,
                font_family="times",
                color_hex="#1F2937",
                align="left",
            ),
            TextRegionSpec(
                region_key="award_details_box",
                role="callout",
                x_pt=36.0,
                y_pt=620.0,
                width_pt=523.28,
                height_pt=100.0,
                font_size_min=9.5,
                font_size_max=11.0,
                font_family="helv",
                color_hex="#1F2937",
            ),
        ],
        image_regions=[
            ImageRegionSpec(
                region_key="victory_team_img",
                role="hero",
                x_pt=36.0,
                y_pt=325.0,
                width_pt=250.0,
                height_pt=260.0,
                aspect_ratio="4:3",
                fit_mode="cover",
            ),
            ImageRegionSpec(
                region_key="victory_award_img",
                role="secondary",
                x_pt=309.28,
                y_pt=325.0,
                width_pt=250.0,
                height_pt=260.0,
                aspect_ratio="4:3",
                fit_mode="cover",
            ),
        ],
        caption_regions=[
            CaptionRegionSpec(
                region_key="caption_team",
                associated_image_key="victory_team_img",
                x_pt=36.0,
                y_pt=590.0,
                width_pt=250.0,
                height_pt=25.0,
                max_words=12,
            ),
            CaptionRegionSpec(
                region_key="caption_award",
                associated_image_key="victory_award_img",
                x_pt=309.28,
                y_pt=590.0,
                width_pt=250.0,
                height_pt=25.0,
                max_words=12,
            ),
        ],
    )


def _build_project_page_spec() -> PageTypeSpec:
    return PageTypeSpec(
        page_type="project",
        display_name="Engineering Project Showcase",
        description="Focuses on capstone engineering prototypes, hardware demos, and patents.",
        maximum_images=2,
        headline_limits={"max_chars": 100, "max_words": 14},
        body_limits={"min_words": 50, "max_words": 320},
        text_regions=[
            TextRegionSpec(
                region_key="project_headline",
                role="headline",
                x_pt=36.0,
                y_pt=45.0,
                width_pt=523.28,
                height_pt=45.0,
                font_size_min=16.0,
                font_size_max=20.0,
                font_family="times-bold",
                color_hex="#1F2937",
            ),
            TextRegionSpec(
                region_key="project_body",
                role="body",
                x_pt=36.0,
                y_pt=100.0,
                width_pt=300.0,
                height_pt=380.0,
                font_size_min=9.5,
                font_size_max=11.0,
                font_family="times",
                color_hex="#1F2937",
                align="justify",
            ),
            TextRegionSpec(
                region_key="project_specs_box",
                role="callout",
                x_pt=36.0,
                y_pt=500.0,
                width_pt=523.28,
                height_pt=120.0,
                font_size_min=9.0,
                font_size_max=10.0,
                font_family="helv",
                color_hex="#1F2937",
            ),
        ],
        image_regions=[
            ImageRegionSpec(
                region_key="project_hardware_img",
                role="hero",
                x_pt=350.0,
                y_pt=100.0,
                width_pt=209.28,
                height_pt=180.0,
                aspect_ratio="16:9",
                fit_mode="cover",
            ),
            ImageRegionSpec(
                region_key="project_team_img",
                role="secondary",
                x_pt=350.0,
                y_pt=300.0,
                width_pt=209.28,
                height_pt=180.0,
                aspect_ratio="16:9",
                fit_mode="cover",
            ),
        ],
        caption_regions=[
            CaptionRegionSpec(
                region_key="caption_hardware",
                associated_image_key="project_hardware_img",
                x_pt=350.0,
                y_pt=282.0,
                width_pt=209.28,
                height_pt=16.0,
                max_words=12,
            ),
            CaptionRegionSpec(
                region_key="caption_team",
                associated_image_key="project_team_img",
                x_pt=350.0,
                y_pt=482.0,
                width_pt=209.28,
                height_pt=16.0,
                max_words=12,
            ),
        ],
    )


def _build_workshop_page_spec() -> PageTypeSpec:
    return PageTypeSpec(
        page_type="workshop",
        display_name="Hands-on Workshop Feature",
        description="Technical masterclass, hands-on kits, and practical development sessions.",
        maximum_images=2,
        headline_limits={"max_chars": 110, "max_words": 15},
        body_limits={"min_words": 50, "max_words": 350},
        text_regions=[
            TextRegionSpec(
                region_key="workshop_headline",
                role="headline",
                x_pt=36.0,
                y_pt=45.0,
                width_pt=523.28,
                height_pt=45.0,
                font_size_min=16.0,
                font_size_max=20.0,
                font_family="times-bold",
                color_hex="#8B0000",
            ),
            TextRegionSpec(
                region_key="workshop_body",
                role="body",
                x_pt=36.0,
                y_pt=95.0,
                width_pt=280.0,
                height_pt=460.0,
                font_size_min=9.5,
                font_size_max=11.0,
                font_family="times",
                color_hex="#1F2937",
                align="justify",
            ),
        ],
        image_regions=[
            ImageRegionSpec(
                region_key="workshop_hands_on_img",
                role="hero",
                x_pt=330.0,
                y_pt=95.0,
                width_pt=229.28,
                height_pt=210.0,
                aspect_ratio="4:3",
                fit_mode="cover",
            ),
            ImageRegionSpec(
                region_key="workshop_group_img",
                role="secondary",
                x_pt=330.0,
                y_pt=340.0,
                width_pt=229.28,
                height_pt=210.0,
                aspect_ratio="4:3",
                fit_mode="cover",
            ),
        ],
        caption_regions=[
            CaptionRegionSpec(
                region_key="caption_hands_on",
                associated_image_key="workshop_hands_on_img",
                x_pt=330.0,
                y_pt=310.0,
                width_pt=229.28,
                height_pt=25.0,
                max_words=14,
            ),
            CaptionRegionSpec(
                region_key="caption_group",
                associated_image_key="workshop_group_img",
                x_pt=330.0,
                y_pt=555.0,
                width_pt=229.28,
                height_pt=25.0,
                max_words=14,
            ),
        ],
    )


def _build_seminar_page_spec() -> PageTypeSpec:
    return PageTypeSpec(
        page_type="seminar",
        display_name="Seminar & Invited Lecture",
        description="Highlights industry resource persons, guest lectures, and academic talks.",
        maximum_images=1,
        headline_limits={"max_chars": 100, "max_words": 14},
        body_limits={"min_words": 50, "max_words": 300},
        text_regions=[
            TextRegionSpec(
                region_key="seminar_headline",
                role="headline",
                x_pt=36.0,
                y_pt=45.0,
                width_pt=523.28,
                height_pt=45.0,
                font_size_min=16.0,
                font_size_max=20.0,
                font_family="times-bold",
                color_hex="#1A365D",
            ),
            TextRegionSpec(
                region_key="speaker_callout",
                role="callout",
                x_pt=36.0,
                y_pt=95.0,
                width_pt=260.0,
                height_pt=130.0,
                font_size_min=9.5,
                font_size_max=11.0,
                font_family="helv",
                color_hex="#1F2937",
            ),
            TextRegionSpec(
                region_key="seminar_body",
                role="body",
                x_pt=36.0,
                y_pt=240.0,
                width_pt=523.28,
                height_pt=450.0,
                font_size_min=9.5,
                font_size_max=11.0,
                font_family="times",
                color_hex="#1F2937",
                align="justify",
            ),
        ],
        image_regions=[
            ImageRegionSpec(
                region_key="speaker_photo",
                role="hero",
                x_pt=310.0,
                y_pt=95.0,
                width_pt=249.28,
                height_pt=130.0,
                aspect_ratio="16:9",
                fit_mode="cover",
            )
        ],
        caption_regions=[
            CaptionRegionSpec(
                region_key="caption_speaker",
                associated_image_key="speaker_photo",
                x_pt=310.0,
                y_pt=230.0,
                width_pt=249.28,
                height_pt=16.0,
                max_words=12,
            )
        ],
    )


def _build_faculty_activity_page_spec() -> PageTypeSpec:
    return PageTypeSpec(
        page_type="faculty_activity",
        display_name="Faculty Activities & Research",
        description="Faculty development programs, doctorates, research grants, and publications.",
        maximum_images=1,
        headline_limits={"max_chars": 100, "max_words": 14},
        body_limits={"min_words": 50, "max_words": 300},
        text_regions=[
            TextRegionSpec(
                region_key="faculty_headline",
                role="headline",
                x_pt=36.0,
                y_pt=45.0,
                width_pt=523.28,
                height_pt=45.0,
                font_size_min=16.0,
                font_size_max=20.0,
                font_family="times-bold",
                color_hex="#8B0000",
            ),
            TextRegionSpec(
                region_key="faculty_body",
                role="body",
                x_pt=36.0,
                y_pt=100.0,
                width_pt=340.0,
                height_pt=480.0,
                font_size_min=9.5,
                font_size_max=11.0,
                font_family="times",
                color_hex="#1F2937",
                align="justify",
            ),
        ],
        image_regions=[
            ImageRegionSpec(
                region_key="faculty_photo",
                role="hero",
                x_pt=390.0,
                y_pt=100.0,
                width_pt=169.28,
                height_pt=220.0,
                aspect_ratio="3:4",
                fit_mode="cover",
            )
        ],
        caption_regions=[
            CaptionRegionSpec(
                region_key="caption_faculty",
                associated_image_key="faculty_photo",
                x_pt=390.0,
                y_pt=325.0,
                width_pt=169.28,
                height_pt=25.0,
                max_words=12,
            )
        ],
    )


def _build_student_activity_page_spec() -> PageTypeSpec:
    return PageTypeSpec(
        page_type="student_activity",
        display_name="Student Activities & Clubs",
        description="NSS, YRC, Rotaract, sports, and cultural college events.",
        maximum_images=3,
        headline_limits={"max_chars": 100, "max_words": 14},
        body_limits={"min_words": 40, "max_words": 280},
        text_regions=[
            TextRegionSpec(
                region_key="student_headline",
                role="headline",
                x_pt=36.0,
                y_pt=45.0,
                width_pt=523.28,
                height_pt=45.0,
                font_size_min=16.0,
                font_size_max=20.0,
                font_family="times-bold",
                color_hex="#1A365D",
            ),
            TextRegionSpec(
                region_key="student_body",
                role="body",
                x_pt=36.0,
                y_pt=100.0,
                width_pt=523.28,
                height_pt=180.0,
                font_size_min=9.5,
                font_size_max=11.0,
                font_family="times",
                color_hex="#1F2937",
                align="justify",
            ),
        ],
        image_regions=[
            ImageRegionSpec(
                region_key="student_img_1",
                role="grid",
                x_pt=36.0,
                y_pt=300.0,
                width_pt=165.0,
                height_pt=200.0,
                aspect_ratio="4:3",
                fit_mode="cover",
            ),
            ImageRegionSpec(
                region_key="student_img_2",
                role="grid",
                x_pt=215.0,
                y_pt=300.0,
                width_pt=165.0,
                height_pt=200.0,
                aspect_ratio="4:3",
                fit_mode="cover",
            ),
            ImageRegionSpec(
                region_key="student_img_3",
                role="grid",
                x_pt=394.28,
                y_pt=300.0,
                width_pt=165.0,
                height_pt=200.0,
                aspect_ratio="4:3",
                fit_mode="cover",
            ),
        ],
        caption_regions=[
            CaptionRegionSpec(
                region_key="caption_s1",
                associated_image_key="student_img_1",
                x_pt=36.0,
                y_pt=505.0,
                width_pt=165.0,
                height_pt=25.0,
                max_words=10,
            ),
            CaptionRegionSpec(
                region_key="caption_s2",
                associated_image_key="student_img_2",
                x_pt=215.0,
                y_pt=505.0,
                width_pt=165.0,
                height_pt=25.0,
                max_words=10,
            ),
            CaptionRegionSpec(
                region_key="caption_s3",
                associated_image_key="student_img_3",
                x_pt=394.28,
                y_pt=505.0,
                width_pt=165.0,
                height_pt=25.0,
                max_words=10,
            ),
        ],
    )


def _build_photo_feature_page_spec() -> PageTypeSpec:
    return PageTypeSpec(
        page_type="photo_feature",
        display_name="Visual Photo Feature Gallery",
        description="Dedicated multi-image showcase (up to 5 images) with narrative captions.",
        maximum_images=5,
        headline_limits={"max_chars": 90, "max_words": 12},
        body_limits={"min_words": 20, "max_words": 120},
        text_regions=[
            TextRegionSpec(
                region_key="feature_headline",
                role="headline",
                x_pt=36.0,
                y_pt=45.0,
                width_pt=523.28,
                height_pt=40.0,
                font_size_min=16.0,
                font_size_max=20.0,
                font_family="times-bold",
                color_hex="#8B0000",
                align="center",
            ),
            TextRegionSpec(
                region_key="feature_intro",
                role="body",
                x_pt=36.0,
                y_pt=90.0,
                width_pt=523.28,
                height_pt=45.0,
                font_size_min=9.5,
                font_size_max=11.0,
                font_family="helv",
                color_hex="#1F2937",
                align="center",
            ),
        ],
        image_regions=[
            ImageRegionSpec(
                region_key="photo_grid_1",
                role="hero",
                x_pt=36.0,
                y_pt=145.0,
                width_pt=300.0,
                height_pt=240.0,
                aspect_ratio="4:3",
                fit_mode="cover",
            ),
            ImageRegionSpec(
                region_key="photo_grid_2",
                role="grid",
                x_pt=350.0,
                y_pt=145.0,
                width_pt=209.28,
                height_pt=115.0,
                aspect_ratio="16:9",
                fit_mode="cover",
            ),
            ImageRegionSpec(
                region_key="photo_grid_3",
                role="grid",
                x_pt=350.0,
                y_pt=270.0,
                width_pt=209.28,
                height_pt=115.0,
                aspect_ratio="16:9",
                fit_mode="cover",
            ),
            ImageRegionSpec(
                region_key="photo_grid_4",
                role="grid",
                x_pt=36.0,
                y_pt=425.0,
                width_pt=250.0,
                height_pt=180.0,
                aspect_ratio="4:3",
                fit_mode="cover",
            ),
            ImageRegionSpec(
                region_key="photo_grid_5",
                role="grid",
                x_pt=309.28,
                y_pt=425.0,
                width_pt=250.0,
                height_pt=180.0,
                aspect_ratio="4:3",
                fit_mode="cover",
            ),
        ],
        caption_regions=[
            CaptionRegionSpec(
                region_key="caption_grid_1",
                associated_image_key="photo_grid_1",
                x_pt=36.0,
                y_pt=390.0,
                width_pt=300.0,
                height_pt=25.0,
                max_words=12,
            ),
            CaptionRegionSpec(
                region_key="caption_grid_4",
                associated_image_key="photo_grid_4",
                x_pt=36.0,
                y_pt=610.0,
                width_pt=250.0,
                height_pt=25.0,
                max_words=12,
            ),
            CaptionRegionSpec(
                region_key="caption_grid_5",
                associated_image_key="photo_grid_5",
                x_pt=309.28,
                y_pt=610.0,
                width_pt=250.0,
                height_pt=25.0,
                max_words=12,
            ),
        ],
    )


def _build_closing_page_spec() -> PageTypeSpec:
    return PageTypeSpec(
        page_type="closing_page",
        display_name="Closing & Editorial Colophon",
        description="Back cover, institutional acknowledgments, and lab editorial credits.",
        maximum_images=1,
        headline_limits={"max_chars": 80, "max_words": 10},
        body_limits={"min_words": 30, "max_words": 150},
        alignment="center",
        text_regions=[
            TextRegionSpec(
                region_key="closing_title",
                role="headline",
                x_pt=36.0,
                y_pt=100.0,
                width_pt=523.28,
                height_pt=45.0,
                font_size_min=18.0,
                font_size_max=22.0,
                font_family="times-bold",
                color_hex="#8B0000",
                align="center",
            ),
            TextRegionSpec(
                region_key="closing_message",
                role="body",
                x_pt=46.0,
                y_pt=160.0,
                width_pt=503.28,
                height_pt=140.0,
                font_size_min=10.0,
                font_size_max=12.0,
                font_family="times",
                color_hex="#1F2937",
                align="center",
            ),
            TextRegionSpec(
                region_key="colophon_credits",
                role="footer",
                x_pt=46.0,
                y_pt=580.0,
                width_pt=503.28,
                height_pt=180.0,
                font_size_min=9.0,
                font_size_max=10.5,
                font_family="helv",
                color_hex="#4B5563",
                align="center",
            ),
        ],
        image_regions=[
            ImageRegionSpec(
                region_key="closing_crest_img",
                role="badge",
                x_pt=217.64,
                y_pt=350.0,
                width_pt=160.0,
                height_pt=160.0,
                aspect_ratio="1:1",
                fit_mode="contain",
            )
        ],
    )


def get_siet_default_v1_template() -> MagazineTemplateSpec:
    """Returns the standardized SIET_DEFAULT_V1 magazine template specification."""
    return MagazineTemplateSpec(
        template_id="SIET_DEFAULT_V1",
        name="SIET Standard Issue Template (Default v1)",
        version="1.0",
        description="Official SIET publication template with configuration-driven geometry and strict styling.",
        primary_color="#8B0000",
        secondary_color="#1A365D",
        background_color="#FDFBF7",
        text_color="#1F2937",
        supported_page_types={
            "cover": _build_cover_page_spec(),
            "contents": _build_contents_page_spec(),
            "event": _build_event_page_spec(),
            "achievement_victory": _build_achievement_victory_page_spec(),
            "project": _build_project_page_spec(),
            "workshop": _build_workshop_page_spec(),
            "seminar": _build_seminar_page_spec(),
            "faculty_activity": _build_faculty_activity_page_spec(),
            "student_activity": _build_student_activity_page_spec(),
            "photo_feature": _build_photo_feature_page_spec(),
            "closing_page": _build_closing_page_spec(),
        },
    )
