"""add_documents_and_template_engine_tables

Revision ID: 2801f999c755
Revises: c9d2e1f4a8b7
Create Date: 2026-08-31 09:10:55.682735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2801f999c755'
down_revision: Union[str, Sequence[str], None] = 'c9d2e1f4a8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    op.drop_column('magazines', 'verification_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magazines', sa.Column('verification_logs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.create_table('site_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('site_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('credit_line', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('accent_color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('newsletter_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('featured_domains', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('site_settings_pkey'))
    )
    # ### end Alembic commands ###
