"""add_missing_magazine_fields

Revision ID: 35b9713d0338
Revises: c1a2b3d4e5f6
Create Date: 2026-10-01 11:19:38.222140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35b9713d0338'
down_revision: Union[str, Sequence[str], None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('department_code', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('sources',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('feed_type', sa.String(length=20), nullable=False),
    sa.Column('feed_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_feed_url'), 'sources', ['feed_url'], unique=True)
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_table('sync_logs',
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('sources_checked', sa.Integer(), nullable=False),
    sa.Column('articles_discovered', sa.Integer(), nullable=False),
    sa.Column('articles_new', sa.Integer(), nullable=False),
    sa.Column('articles_duplicate', sa.Integer(), nullable=False),
    sa.Column('articles_failed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('log_details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_id'), 'sync_logs', ['id'], unique=False)
    op.create_table('subcategories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcategories_id'), 'subcategories', ['id'], unique=False)
    op.create_index(op.f('ix_subcategories_slug'), 'subcategories', ['slug'], unique=True)
    op.create_table('source_documents',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('lab_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_id'), 'source_documents', ['id'], unique=False)
    op.create_index(op.f('ix_source_documents_lab_id'), 'source_documents', ['lab_id'], unique=False)
    op.create_table('story_coverage',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=150), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_coverage_id'), 'story_coverage', ['id'], unique=False)
    op.create_index(op.f('ix_story_coverage_news_id'), 'story_coverage', ['news_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('section_label', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_document_chunks_page_number'), 'document_chunks', ['page_number'], unique=False)
    op.create_table('docx_template_blueprints',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('blueprint_json', sa.JSON(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docx_template_blueprints_id'), 'docx_template_blueprints', ['id'], unique=False)
    op.create_index(op.f('ix_docx_template_blueprints_source_document_id'), 'docx_template_blueprints', ['source_document_id'], unique=False)
    op.drop_table('site_settings')
    op.add_column('lab_memberships', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lab_memberships', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_lab_memberships_id'), 'lab_memberships', ['id'], unique=False)
    op.create_unique_constraint('uq_lab_memberships_user_lab', 'lab_memberships', ['user_id', 'lab_id'])
    op.add_column('labs', sa.Column('code', sa.String(length=50), nullable=False))
    op.add_column('labs', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('labs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('labs', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.alter_column('labs', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('labs', 'slug',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_index(op.f('ix_labs_slug'), table_name='labs')
    op.create_index(op.f('ix_labs_slug'), 'labs', ['slug'], unique=True)
    op.create_index(op.f('ix_labs_code'), 'labs', ['code'], unique=True)
    op.create_index(op.f('ix_labs_department_id'), 'labs', ['department_id'], unique=False)
    op.create_index(op.f('ix_labs_name'), 'labs', ['name'], unique=True)
    op.drop_constraint(op.f('labs_domain_id_fkey'), 'labs', type_='foreignkey')
    op.create_foreign_key(None, 'labs', 'domains', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_column('labs', 'domain_id')
    op.alter_column('magazine_pages', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=False)
    op.create_index(op.f('ix_magazine_pages_id'), 'magazine_pages', ['id'], unique=False)
    op.create_index(op.f('ix_magazine_templates_created_by_id'), 'magazine_templates', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_magazine_templates_id'), 'magazine_templates', ['id'], unique=False)
    op.alter_column('magazine_toc_entries', 'heading',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_magazine_toc_entries_id'), 'magazine_toc_entries', ['id'], unique=False)
    op.add_column('magazines', sa.Column('event_name', sa.String(length=255), nullable=True))
    op.add_column('magazines', sa.Column('event_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('magazines', sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('magazines', sa.Column('is_featured', sa.Boolean(), nullable=False))
    op.add_column('magazines', sa.Column('featured_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('magazines', sa.Column('pdf_url', sa.String(length=500), nullable=True))
    op.add_column('magazines', sa.Column('cover_image_url', sa.String(length=500), nullable=True))
    op.add_column('magazines', sa.Column('page_count', sa.Integer(), nullable=False))
    op.add_column('magazines', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.add_column('magazines', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('magazines', sa.Column('cover_pages', sa.JSON(), nullable=True))
    op.add_column('magazines', sa.Column('body_pages', sa.JSON(), nullable=True))
    op.add_column('magazines', sa.Column('gallery_images', sa.JSON(), nullable=True))
    op.alter_column('magazines', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED', name='contentstatus'),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_index(op.f('ix_magazines_created_by_id'), 'magazines', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_magazines_event_date'), 'magazines', ['event_date'], unique=False)
    op.create_index(op.f('ix_magazines_event_name'), 'magazines', ['event_name'], unique=False)
    op.create_index(op.f('ix_magazines_template_id'), 'magazines', ['template_id'], unique=False)
    op.create_index(op.f('ix_magazines_template_version_id'), 'magazines', ['template_version_id'], unique=False)
    op.create_foreign_key(None, 'magazines', 'template_versions', ['template_version_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('media_lab_id_fkey'), 'media', type_='foreignkey')
    op.add_column('news', sa.Column('simple_explanation', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('detailed_sections', sa.JSON(), nullable=True))
    op.add_column('news', sa.Column('content_depth', sa.String(length=20), nullable=False))
    op.add_column('news', sa.Column('content_summary', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('detailed_summary', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('key_points', sa.JSON(), nullable=True))
    op.add_column('news', sa.Column('technical_details', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('why_it_matters', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('student_relevance', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('department', sa.String(length=50), nullable=False))
    op.add_column('news', sa.Column('subcategory', sa.String(length=100), nullable=True))
    op.add_column('news', sa.Column('tags_list', sa.JSON(), nullable=True))
    op.add_column('news', sa.Column('coverage_count', sa.Integer(), nullable=False))
    op.add_column('news', sa.Column('verification_status', sa.String(length=30), nullable=False))
    op.add_column('news', sa.Column('source_id', sa.Integer(), nullable=True))
    op.add_column('news', sa.Column('canonical_url', sa.String(length=500), nullable=True))
    op.add_column('news', sa.Column('author', sa.String(length=150), nullable=True))
    op.add_column('news', sa.Column('image_url', sa.String(length=600), nullable=True))
    op.add_column('news', sa.Column('image_caption', sa.String(length=300), nullable=True))
    op.add_column('news', sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('news', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('news', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('news', sa.Column('duplicate_of_id', sa.Integer(), nullable=True))
    op.add_column('news', sa.Column('processing_status', sa.String(length=20), nullable=False))
    op.add_column('news', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.add_column('news', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('news', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('news', 'slug',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=350),
               existing_nullable=False)
    op.alter_column('news', 'source_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.create_index(op.f('ix_news_content_hash'), 'news', ['content_hash'], unique=False)
    op.create_index(op.f('ix_news_is_archived'), 'news', ['is_archived'], unique=False)
    op.create_foreign_key(None, 'news', 'sources', ['source_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'news', 'news', ['duplicate_of_id'], ['id'], ondelete='SET NULL')
    op.add_column('template_embeddings', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('template_embeddings', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_template_embeddings_id'), 'template_embeddings', ['id'], unique=False)
    op.add_column('template_lab_assignments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('template_lab_assignments', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_template_lab_assignments_id'), 'template_lab_assignments', ['id'], unique=False)
    op.create_unique_constraint('uq_template_lab_assignments_template_lab', 'template_lab_assignments', ['template_id', 'lab_id'])
    op.create_index(op.f('ix_template_pages_id'), 'template_pages', ['id'], unique=False)
    # Fresh databases create template_pages WITHOUT a version column
    # (e4b4ce451d00), while the legacy dev DB still had it. Drop it only
    # when present so `alembic upgrade head` works on both.
    op.execute("ALTER TABLE template_pages DROP COLUMN IF EXISTS version")
    op.create_index(op.f('ix_template_regions_id'), 'template_regions', ['id'], unique=False)
    op.add_column('template_versions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('template_versions', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_template_versions_created_by_id'), 'template_versions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_template_versions_id'), 'template_versions', ['id'], unique=False)
    op.drop_column('users', 'reset_token_hash')
    op.drop_column('users', 'verification_token_expiry')
    op.drop_column('users', 'verification_token_hash')
    op.drop_column('users', 'reset_token_expiry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token_expiry', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('verification_token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('verification_token_expiry', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('reset_token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_template_versions_id'), table_name='template_versions')
    op.drop_index(op.f('ix_template_versions_created_by_id'), table_name='template_versions')
    op.drop_column('template_versions', 'version')
    op.drop_column('template_versions', 'deleted_at')
    op.drop_index(op.f('ix_template_regions_id'), table_name='template_regions')
    op.add_column('template_pages', sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_template_pages_id'), table_name='template_pages')
    op.drop_constraint('uq_template_lab_assignments_template_lab', 'template_lab_assignments', type_='unique')
    op.drop_index(op.f('ix_template_lab_assignments_id'), table_name='template_lab_assignments')
    op.drop_column('template_lab_assignments', 'version')
    op.drop_column('template_lab_assignments', 'deleted_at')
    op.drop_index(op.f('ix_template_embeddings_id'), table_name='template_embeddings')
    op.drop_column('template_embeddings', 'version')
    op.drop_column('template_embeddings', 'deleted_at')
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_index(op.f('ix_news_is_archived'), table_name='news')
    op.drop_index(op.f('ix_news_content_hash'), table_name='news')
    op.alter_column('news', 'source_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('news', 'slug',
               existing_type=sa.String(length=350),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    op.alter_column('news', 'title',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('news', 'archived_at')
    op.drop_column('news', 'is_archived')
    op.drop_column('news', 'processing_status')
    op.drop_column('news', 'duplicate_of_id')
    op.drop_column('news', 'content_hash')
    op.drop_column('news', 'processed_at')
    op.drop_column('news', 'fetched_at')
    op.drop_column('news', 'image_caption')
    op.drop_column('news', 'image_url')
    op.drop_column('news', 'author')
    op.drop_column('news', 'canonical_url')
    op.drop_column('news', 'source_id')
    op.drop_column('news', 'verification_status')
    op.drop_column('news', 'coverage_count')
    op.drop_column('news', 'tags_list')
    op.drop_column('news', 'subcategory')
    op.drop_column('news', 'department')
    op.drop_column('news', 'student_relevance')
    op.drop_column('news', 'why_it_matters')
    op.drop_column('news', 'technical_details')
    op.drop_column('news', 'key_points')
    op.drop_column('news', 'detailed_summary')
    op.drop_column('news', 'content_summary')
    op.drop_column('news', 'content_depth')
    op.drop_column('news', 'detailed_sections')
    op.drop_column('news', 'simple_explanation')
    op.create_foreign_key(op.f('media_lab_id_fkey'), 'media', 'labs', ['lab_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'magazines', type_='foreignkey')
    op.drop_index(op.f('ix_magazines_template_version_id'), table_name='magazines')
    op.drop_index(op.f('ix_magazines_template_id'), table_name='magazines')
    op.drop_index(op.f('ix_magazines_event_name'), table_name='magazines')
    op.drop_index(op.f('ix_magazines_event_date'), table_name='magazines')
    op.drop_index(op.f('ix_magazines_created_by_id'), table_name='magazines')
    op.alter_column('magazines', 'status',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED', name='contentstatus'),
               existing_nullable=False)
    op.drop_column('magazines', 'gallery_images')
    op.drop_column('magazines', 'body_pages')
    op.drop_column('magazines', 'cover_pages')
    op.drop_column('magazines', 'processed_at')
    op.drop_column('magazines', 'failure_reason')
    op.drop_column('magazines', 'page_count')
    op.drop_column('magazines', 'cover_image_url')
    op.drop_column('magazines', 'pdf_url')
    op.drop_column('magazines', 'featured_until')
    op.drop_column('magazines', 'is_featured')
    op.drop_column('magazines', 'issue_date')
    op.drop_column('magazines', 'event_date')
    op.drop_column('magazines', 'event_name')
    op.drop_index(op.f('ix_magazine_toc_entries_id'), table_name='magazine_toc_entries')
    op.alter_column('magazine_toc_entries', 'heading',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_magazine_templates_id'), table_name='magazine_templates')
    op.drop_index(op.f('ix_magazine_templates_created_by_id'), table_name='magazine_templates')
    op.drop_index(op.f('ix_magazine_pages_id'), table_name='magazine_pages')
    op.alter_column('magazine_pages', 'image_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('labs', sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'labs', type_='foreignkey')
    op.create_foreign_key(op.f('labs_domain_id_fkey'), 'labs', 'domains', ['domain_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_labs_name'), table_name='labs')
    op.drop_index(op.f('ix_labs_department_id'), table_name='labs')
    op.drop_index(op.f('ix_labs_code'), table_name='labs')
    op.drop_index(op.f('ix_labs_slug'), table_name='labs')
    op.create_index(op.f('ix_labs_slug'), 'labs', ['slug'], unique=False)
    op.alter_column('labs', 'slug',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('labs', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('labs', 'version')
    op.drop_column('labs', 'deleted_at')
    op.drop_column('labs', 'department_id')
    op.drop_column('labs', 'code')
    op.drop_constraint('uq_lab_memberships_user_lab', 'lab_memberships', type_='unique')
    op.drop_index(op.f('ix_lab_memberships_id'), table_name='lab_memberships')
    op.drop_column('lab_memberships', 'version')
    op.drop_column('lab_memberships', 'deleted_at')
    op.create_table('site_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('site_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('credit_line', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('accent_color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('newsletter_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('featured_domains', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('site_settings_pkey'))
    )
    op.drop_index(op.f('ix_docx_template_blueprints_source_document_id'), table_name='docx_template_blueprints')
    op.drop_index(op.f('ix_docx_template_blueprints_id'), table_name='docx_template_blueprints')
    op.drop_table('docx_template_blueprints')
    op.drop_index(op.f('ix_document_chunks_page_number'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_story_coverage_news_id'), table_name='story_coverage')
    op.drop_index(op.f('ix_story_coverage_id'), table_name='story_coverage')
    op.drop_table('story_coverage')
    op.drop_index(op.f('ix_source_documents_lab_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_id'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_subcategories_slug'), table_name='subcategories')
    op.drop_index(op.f('ix_subcategories_id'), table_name='subcategories')
    op.drop_table('subcategories')
    op.drop_index(op.f('ix_sync_logs_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_feed_url'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
