"""create_template_embeddings_table

Revision ID: 797e7d74a93d
Revises: 901bb0997d46
Create Date: 2026-09-10 15:39:29.522338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '797e7d74a93d'
down_revision: Union[str, Sequence[str], None] = '901bb0997d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_embeddings',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=100), nullable=False),
    sa.Column('example_key', sa.String(length=100), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['magazine_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_embeddings_id'), 'template_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_template_embeddings_section_type'), 'template_embeddings', ['section_type'], unique=False)
    op.create_index(op.f('ix_template_embeddings_template_id'), 'template_embeddings', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_embeddings_template_id'), table_name='template_embeddings')
    op.drop_index(op.f('ix_template_embeddings_section_type'), table_name='template_embeddings')
    op.drop_index(op.f('ix_template_embeddings_id'), table_name='template_embeddings')
    op.drop_table('template_embeddings')
    # ### end Alembic commands ###
