"""add_soft_delete_columns_to_magazine_template_tables

Revision ID: 7c9d2f4a1b3e
Revises: 35b9713d0338
Create Date: 2026-10-07

Fixes schema drift between ORM models (BaseModelMixin) and alembic history:
- ``magazine_pages``, ``magazine_toc_entries`` and ``template_regions`` are
  created by e4b4ce451d00 WITHOUT ``deleted_at``/``version`` columns, but the
  ORM models inherit both from ``BaseModelMixin``.
- ``template_pages`` is created WITHOUT ``deleted_at`` (and its ``version``
  attribute is a relationship to ``TemplateVersion``, so no ``version``
  column exists in metadata).

All statements are idempotent (``IF NOT EXISTS``) so the migration runs
cleanly on fresh databases as well as on legacy databases where the columns
may already exist (e.g. via ``Base.metadata.create_all`` / ``sync_db.py``).
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7c9d2f4a1b3e'
down_revision: Union[str, Sequence[str], None] = '35b9713d0338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema — idempotent soft-delete column backfill."""
    conn = op.get_bind()
    conn.execute(sa.text(
        "ALTER TABLE magazine_pages "
        "ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ, "
        "ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;"
    ))
    conn.execute(sa.text(
        "ALTER TABLE magazine_toc_entries "
        "ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ, "
        "ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;"
    ))
    conn.execute(sa.text(
        "ALTER TABLE template_regions "
        "ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ, "
        "ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;"
    ))
    conn.execute(sa.text(
        "ALTER TABLE template_pages ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;"
    ))

    # ── site_settings ─────────────────────────────────────────────────────
    # The head revision (35b9713d0338, autogenerated) drops ``site_settings``,
    # but the ORM model ``app.modules.settings.models.SiteSettings`` still
    # declares it, so a pure ``alembic upgrade head`` build is missing the
    # table. Recreate it idempotently (with the BaseModelMixin columns) and
    # re-seed the default row so ORM/metadata parity holds on fresh DBs.
    conn.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS site_settings (
            id                 SERIAL PRIMARY KEY,
            created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
            deleted_at         TIMESTAMPTZ,
            version            INTEGER NOT NULL DEFAULT 1,
            site_name          VARCHAR(200) NOT NULL DEFAULT 'SIET News',
            credit_line        TEXT NOT NULL DEFAULT 'AI Research Lab',
            accent_color       VARCHAR(50) NOT NULL DEFAULT '#0F2B5C',
            newsletter_enabled BOOLEAN NOT NULL DEFAULT TRUE,
            featured_domains   VARCHAR(500) NOT NULL DEFAULT 'machine-learning, robotics'
        )
    """))
    conn.execute(sa.text("""
        INSERT INTO site_settings AS s
            (id, site_name, credit_line, accent_color, newsletter_enabled, featured_domains)
        VALUES
            (1, 'SIET News',
             'AI Research Lab · Sri Shakthi Institute of Engineering and Technology',
             '#0F2B5C', TRUE, 'machine-learning, robotics')
        ON CONFLICT (id) DO NOTHING
    """))


def downgrade() -> None:
    """Downgrade schema — drop the backfilled columns when present."""
    conn = op.get_bind()
    conn.execute(sa.text("ALTER TABLE magazine_pages DROP COLUMN IF EXISTS version;"))
    conn.execute(sa.text("ALTER TABLE magazine_pages DROP COLUMN IF EXISTS deleted_at;"))
    conn.execute(sa.text("ALTER TABLE magazine_toc_entries DROP COLUMN IF EXISTS version;"))
    conn.execute(sa.text("ALTER TABLE magazine_toc_entries DROP COLUMN IF EXISTS deleted_at;"))
    conn.execute(sa.text("ALTER TABLE template_regions DROP COLUMN IF EXISTS version;"))
    conn.execute(sa.text("ALTER TABLE template_regions DROP COLUMN IF EXISTS deleted_at;"))
    conn.execute(sa.text("ALTER TABLE template_pages DROP COLUMN IF EXISTS deleted_at;"))
