"""add_editorial_plan_and_orchestrator_score

Revision ID: 901bb0997d46
Revises: e4b4ce451d00
Create Date: 2026-08-31 09:37:51.960610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '901bb0997d46'
down_revision: Union[str, Sequence[str], None] = 'e4b4ce451d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TABLE magazines ADD COLUMN IF NOT EXISTS editorial_plan JSON;")
    op.execute("ALTER TABLE magazines ADD COLUMN IF NOT EXISTS orchestrator_score FLOAT;")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('magazines', 'orchestrator_score')
    op.drop_column('magazines', 'editorial_plan')
    # ### end Alembic commands ###
