"""add_editorial_plan_and_orchestrator_score

Revision ID: 901bb0997d46
Revises: e4b4ce451d00
Create Date: 2026-08-31 09:37:51.960610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '901bb0997d46'
down_revision: Union[str, Sequence[str], None] = 'e4b4ce451d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    op.add_column('magazines', sa.Column('editorial_plan', sa.JSON(), nullable=True))
    op.add_column('magazines', sa.Column('orchestrator_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('magazines', 'orchestrator_score')
    op.drop_column('magazines', 'editorial_plan')
    op.create_table('site_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('site_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('credit_line', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('accent_color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('newsletter_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('featured_domains', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('site_settings_pkey'))
    )
    # ### end Alembic commands ###
