"""add_example_outputs_to_magazine_templates

Revision ID: e4b4ce451d00
Revises: 2801f999c755
Create Date: 2026-08-31 09:14:54.509412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4b4ce451d00'
down_revision: Union[str, Sequence[str], None] = '2801f999c755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    op.add_column('magazine_templates', sa.Column('example_outputs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('magazine_templates', 'example_outputs')
    op.create_table('site_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('site_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('credit_line', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('accent_color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('newsletter_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('featured_domains', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('site_settings_pkey'))
    )
    # ### end Alembic commands ###
